name: Build and Run Integration Tests

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - '**'  # Run on all pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install build and test dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libx11-dev \
            libxft-dev \
            libxpm-dev \
            fonts-terminus-otb \
            xdotool \
            imagemagick \
            x11-apps \
            xvfb
          sudo fc-cache -fv

      # Step 3: Build the app using Makefile
      - name: Build the application
        run: |
          make

      # Step 4: Start the Xvfb (Virtual Framebuffer)
      - name: Start Xvfb (Virtual Framebuffer)
        run: |
          # Start Xvfb on display :99
          Xvfb :99 -screen 0 800x600x24 &
          # Set the DISPLAY environment variable to use the virtual display
          export DISPLAY=:99
          # waiting for framebuffer
          sleep 3

          fc-list
          # run tests
          make test

      # Step 5: Upload screenshots and diffs as artifacts if tests fail
      - name: Upload screenshots as artifacts (for debugging)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: integration-tests
